spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/pricealerter
spring.datasource.username=postgres
spring.datasource.password=negm
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=ZmFrZVNlY3JldEtleUZvckpXVFRlc3RpbmdQdXJwb3Nlc09ubHk=
jwt.access-expiration=86400000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
